export const MIN_COMPOSER_HEIGHT = 40;
export const MAX_COMPOSER_HEIGHT = 200;

export const MIN_INPUT_TOOLBAR_HEIGHT = MIN_COMPOSER_HEIGHT;

export const DATE_FORMAT = "ll";
export const TIME_FORMAT = "LT";

export const TEST_ID = {
  GIFTED_CHAT_WRAPPER: "GC_WRAPPER",
  COMPOSER_ID: "Message",
  GIFTED_CHAT_LOADING_WRAPPER: "GC_LOADING_CONTAINER",
  SEND_TOUCHABLE: "GC_SEND_TOUCHABLE",
  BUBBLE_CONTENT: "GC_BUBBLE_CONTENT",
  AVATAR: "GC_AVATAR",
  MEDIA_REACTIONS: "GC_MEDIA_REACTIONS",
  DM_ICON: "GC_DM_ICON",
  GROUP_PARTICIPANTS: "GC_GROUP_PARTICIPANTS",
  CONTACTS_SUMMARY: "GC_CONTACTS_SUMMARY",
  INVITE_CARD: "GC_INVITE_CARD",
  CONTACT_CARD: "GC_CONTACT_CARD",
  GROUP_CARD: "GC_GROUP_CARD",
  CONTINUED_FROM: "GC_CONTINUED_FROM",
  CONTINUED_TO: "GC_CONTINUED_TO",
  LOCATION_TAG: "GC_LOCATION_TAG",
  QUICK_REACTIONS: "GC_QUICK_REACTIONS",
  MESSAGE_TEXT: "GC_MESSAGE_TEXT",
  POST_MAIN: "GC_POST_MAIN",
  POST_IN_FEED: "GC_POST_IN_FEED",
  POST_BODY: "GC_POST_BODY",
  POST_TOP_ROW: "GC_POST_TOP_ROW",
  POST_HOVER_MENU: "GC_POST_HOVER_MENU",
  POST_FLOATING_MENU: "GC_POST_FLOATING_MENU",
  HANGING_MEDIA_REACTIONS_AND_EDITED: "GC_HANGING_MEDIA_REACTIONS_AND_EDITED",
  // Added for DiscussionApp unit testing with real components:
  DISCUSSION_APP_CONTAINER: "GC_DISCUSSION_APP_CONTAINER",
  DISCUSSION_APP_LOADING: "GC_DISCUSSION_APP_LOADING",
  DISCUSSION_APP_ERROR: "GC_DISCUSSION_APP_ERROR",
  // Added for MessageImage unit testing with real components:
  MESSAGE_IMAGE_CONTAINER: "GC_MESSAGE_IMAGE_CONTAINER",
  MESSAGE_IMAGE_VIDEO: "GC_MESSAGE_IMAGE_VIDEO",
  MESSAGE_IMAGE_IMAGE: "GC_MESSAGE_IMAGE_IMAGE",
  MESSAGE_IMAGE_PLAY_BUTTON: "GC_MESSAGE_IMAGE_PLAY_BUTTON",
  MESSAGE_MEDIA_SCROLL_VIEW: "GC_MESSAGE_MEDIA_SCROLL_VIEW",
  MESSAGE_MEDIA_ITEM: "GC_MESSAGE_MEDIA_ITEM",
  MESSAGE_MEDIA_GALLERY: "GC_MESSAGE_MEDIA_GALLERY",
  MESSAGE_MEDIA_CLOSE_BUTTON: "GC_MESSAGE_MEDIA_CLOSE_BUTTON",
};
